### ISSUE TITLE
Always printing. ALWAYS.

### ISSUE THREAD

**Issue by spiderman20084** [desktop-dart/duration#6]
First of all thanks for the great plugin.
Second of all is there a way to get the duration without printing it to the terminal?

It is super annoying doing debug with this especially if i'm checking for the duration every second.
That means a print statement in every second.

Thanks again for plugin it just needs some more locales. 
If you need help with the Arabic locale send me a message.

**Comment by tejainece** [comment]
https://pub.dev/documentation/duration/latest/duration/prettyDuration.html
https://pub.dev/documentation/duration/latest/duration/prettySeconds.html
https://pub.dev/documentation/duration/latest/duration/prettyMilliseconds.html

These return strings instead of printing.

Do send a PR with Arabic locale.

**Comment by jeffjose** [comment]
Opened https://github.com/desktop-dart/duration/issues/31
